### ISSUE TITLE
loops, re-use and more than one result?

### ISSUE THREAD

**Issue by j2l** [aveic/vax#2]
Hi,
I tried reading the PDF, but I don't read Russian (or is it another language, sorry).
Is it possible to have loops, with incremental index (i) like:
for i, i<10, i++
   do this
or even more basic ones, using if, then with a local variable.
see:
https://upload.wikimedia.org/wikipedia/commons/5/5c/Scc.png

And what about re-using a procedure (subroutine)? I can't make function work using the editor alone.
And updating global variables?
And finally, is it possible to have more than one result without breaking VAX.composeTrees?

Thanks,

**Comment by j2l** [comment]
I searched about loops in walk tree but didn't get how to implement them.
May be using Functions? Any example?

**Comment by evazamtz** [comment]
Considering loops there is a restriction, saying that one input socket can be used only once. So there is a maximum of one wire, that can be attached to an input socket. (Though unlimited number of wires can be attached to an output socket). It makes sense, since how else would u know what wire to choose from. Also, the function `VAX.composeTrees` doesn't allow cyclic wires, so it will throw an error, like this one:
`Error: Node 49 is already present in graph parents: 72, 67, 49, 45, 41`
But you can still imitate loops with multi sockets nodes. Of course, in this case, u have to know the maximum number of inputs that u will need, but I doubt u would generally need more than five. I made a simple example using 2-inputs-node, to imitate your loop:
![default](https://user-images.githubusercontent.com/1138177/34673890-e2b74da0-f494-11e7-8c33-f570842443f8.png)
As you can see there is no connection from _c_ to _g_, but that could be avoided with a 3-socket-node, which u can easily create.
In this example, you can't use `VAX.composeTrees`, since a cyclic graph can't be encoded into a tree, so you have to resort to a `VAX.saveGraph()` function which will give u a separate array of nodes and wires, and you're free to interpret it as u like. For instance, the above-mentioned graph will give smth like:
```javascript
{
  "nodes": [
    {
      "id": 41,
      "c": "And",
      "x": 443,
      "y": 431
    },
    {
      "id": 45,
      "c": "And",
      "x": 443,
      "y": 201
    },
    {
      "id": 49,
      "c": "And",
      "x": 673,
      "y": 207
    },
    {
      "id": 53,
      "c": "And",
      "x": 655,
      "y": 426
    },
    {
      "id": 61,
      "c": "And",
      "x": 931,
      "y": 433
    },
    {
      "id": 67,
      "c": "And",
      "x": 928,
      "y": 207
    },
    {
      "id": 72,
      "c": "And",
      "x": 1185,
      "y": 209
    },
    {
      "id": 77,
      "c": "And",
      "x": 1173,
      "y": 444
    }
  ],
  "wires": [
    [
      45,
      "O",
      49,
      "A"
    ],
    [
      49,
      "O",
      41,
      "A"
    ],
    [
      41,
      "O",
      53,
      "A"
    ],
    [
      41,
      "O",
      45,
      "A"
    ],
    [
      53,
      "O",
      61,
      "B"
    ],
    [
      61,
      "O",
      53,
      "B"
    ],
    [
      49,
      "O",
      67,
      "A"
    ],
    [
      67,
      "O",
      72,
      "A"
    ],
    [
      77,
      "O",
      61,
      "A"
    ],
    [
      61,
      "O",
      77,
      "A"
    ],
    [
      72,
      "O",
      67,
      "B"
    ],
    [
      77,
      "O",
      72,
      "B"
    ],
    [
      72,
      "O",
      77,
      "B"
    ]
  ]
}
```

> And what about re-using a procedure (subroutine)? I can't make function work using the editor alone.

Yes, you can make your own user functions using the editor. Probably problems with compiling them.

> And finally, is it possible to have more than one result without breaking VAX.composeTrees?

Yes, `VAX.composeTrees` returns as many separate trees as they're present on the blueprint.

> And updating global variables?

Sorry, but I don't get the question about global variables. The editor itself is just a visual manager of nodes. It has nothing to do with any certain programming language whatsoever. You can provide the schema with the nodes you want, for e.g. "AssingToGlobalVar", "GetValueOfGlobalVar".

It would much more clear for me if you provide an example of what you're trying to accomplish with VAX.

**Comment by evazamtz** [comment]
> Is it possible to have loops, with incremental index (i) like:
> for i, i<10, i++
> do this
> or even more basic ones, using if, then with a local variable.

Well, once again it's up to you to design a schema that fits your needs:
![default](https://user-images.githubusercontent.com/1138177/34675696-7a4abaa2-f49b-11e7-9723-8d32c5b555e8.png)

**Comment by j2l** [comment]
Very detailed reply, thank you very much.
I tested many different situations and was about to switch to something else but I'll continue on VAX and may come with more detailed questions.
