### ISSUE TITLE
function using [A] or [A, B] or [A, B, C] is not created, only function without parameter (and no output)

### ISSUE THREAD

**Issue by j2l** [aveic/vax#3]
As you can see, I successfully created 4 functions and only one is proposed in the main blueprint component menu:
![image](https://user-images.githubusercontent.com/65325/34491739-f5cd14ce-efe4-11e7-93b6-17047e9ff9ee.png)

I don't understand what is the use of a function without input and output.
Or may be I didn't understand how to add them to it.

**Comment by evazamtz** [comment]
You have to compile them first (with the Ctrl+E) in order to be visible in the components list. Probably, smth went wrong during compilation of other functions, therefore they're enlisted.
I know, the interface of the compilation of the user functions is far from intuitive, guess it requires a lot of work.

**Comment by j2l** [comment]
Ok, thanks!
